{{- if eq .Values.database.secret  "cd2024bfs3g1-dev-db-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: cd2024bfs1g1-dev-db-secret
  annotations:
    "helm.sh/resource-policy": "keep"  
data:
  password: {{  "testuser"  | b64enc }}
  user: {{ "testuser" | b64enc }}
  postgresql-password: {{  "cd2024bfs1g1"  | b64enc }}
{{- end }}